upd

diff --git a/.github/workflows/rubyonrails.yml b/.github/workflows/rubyonrails.yml
--- a/.github/workflows/rubyonrails.yml
+++ b/.github/workflows/rubyonrails.yml
@@ -7,19 +7,50 @@ on:
   pull_request:
     branches:
       - main
-
 jobs:
-  mysql_test:
+  build_and_test:
     runs-on: ubuntu-latest
     services:
       db:
         image: mysql:latest
         env:
-          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
+          MYSQL_ROOT_PASSWORD: password  # Consider using GitHub Secrets here
+          MYSQL_DATABASE: EventManager_test
+          MYSQL_USER: user
+          MYSQL_PASSWORD: password
         ports:
           - 3306:3306
+    env:
+      MYSQL_USER: user
+      MYSQL_PASSWORD: password
+      HOST: db
+      HOST_DEVELOPMENT: db
+      HOST_TEST: db
+      RAILS_MAX_THREADS: 5
+      
     steps:
-    - name: Check MySQL
+    - uses: actions/checkout@v2
+    - name: Set up Ruby
+      uses: ruby/setup-ruby@v1
+      with:
+        ruby-version: '3.3'
+    - name: Install dependencies
       run: |
-        sleep 10
-        mysql -h db -uroot -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"
+        sudo apt-get update -qq
+        sudo apt-get install -y libpq-dev nodejs
+        gem install bundler
+        bundle install
+    - name: Wait for database
+      run: |
+        echo "Waiting for MySQL..."
+     
+        for i in {1..15}; do
+          nc -z $HOST 3306 && echo "MySQL is up" && exit 0
+          echo "Retrying..."
+          sleep 4
+        done
+        echo "MySQL failed to start" && exit 1
+
+    - name: Run tests
+      run: |
+        bundle exec rspec
